[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
jellyfin-sdk-rust = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
